"""add base passwords for users

Revision ID: 3de1801ee648
Revises: 4f3bbd6bc9d9
Create Date: 2026-06-12 13:27:31.473130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de1801ee648'
down_revision: Union[str, Sequence[str], None] = '4f3bbd6bc9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE users SET password = '123'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
